# TODO: Migrate to vyos-build (https://github.com/vyos/vyos-build) for building
# VyOS images instead of Packer. The vyos-build approach provides better support
# for customization and doesn't require nested virtualization in CI.
#
# This workflow is currently disabled pending the migration.

name: Build VyOS Image

on:
  workflow_dispatch:
    inputs:
      placeholder:
        description: 'Workflow disabled - see TODO comment'
        type: string
        default: 'disabled'

jobs:
  disabled:
    if: false  # Workflow is disabled
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is disabled pending migration to vyos-build"
